#!/bin/sh

brew tap phinze/homebrew-cask
brew install brew-cask

brew cask install java --appdir=/Applications
brew cask install google-chrome --appdir=/Applications
brew cask install firefox --appdir=/Applications
brew cask install spotify --appdir=/Applications
brew cask install hipchat --appdir=/Applications
brew cask install tower --appdir=/Applications
brew cask install dropbox --appdir=/Applications
brew cask install navicat-for-postgresql --appdir=/Applications
brew cask install pgadmin3 --appdir=/Applications
brew cask install rubymine --appdir=/Applications
brew cask install textmate --appdir=/Applications
brew cask install transmission --appdir=/Applications
brew cask install vlc --appdir=/Applications
brew cask install vmware-fusion --appdir=/Applications
brew cask install wireshark --appdir=/Applications

brew cask install flux
brew cask install lastpass-universal
brew cask install silverlight
brew cask install authy-bluetooth
brew cask install little-snith
brew cask install tunnelblick
